name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: '>=1.17.7'
      #     cache: true
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - run: goreleaser release --rm-dist